os:
  - linux
  
branches:
  only:
    - master
  
language: cpp

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - qmake -version
  
script:
  - qmake
  - make
  
#addons:
#  apt:
#    packages:
#      - qtbase5-dev
