os:
  - linux
  
branches:
  only:
    - master
  
language: cpp

env:
  - CONFIG=release QT=qt5

sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - qmake -version
  
#script:
#  - qmake
#  - make
  
#addons:
#  apt:
#    packages:
#      - qtbase5-dev
